# Generated by Django 5.1.2 on 2024-10-21 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('option1', models.TextField()),
                ('option2', models.TextField()),
                ('option3', models.TextField()),
                ('option4', models.TextField()),
                ('correct_option', models.TextField()),
                ('category', models.CharField(choices=[('category1', 'Category 1'), ('category2', 'Category 2'), ('category3', 'Category 3')], max_length=50)),
                ('subject', models.CharField(choices=[('subject1', 'Subject 1'), ('subject2', 'Subject 2'), ('subject3', 'Subject 3')], max_length=50)),
            ],
        ),
    ]
