# Generated by Django 5.1.2 on 2024-10-21 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NMC_MCQ', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('MBBS', 'MBBS'), ('BDS', 'BDS'), ('MS', 'MS')], max_length=50),
        ),
    ]
