# Generated by Django 5.1.2 on 2024-10-21 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NMC_MCQ', '0002_alter_question_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.CharField(choices=[('subject1', 'Surgery'), ('subject2', 'Medicine'), ('subject3', 'Gyane')], max_length=50),
        ),
    ]
