# Generated by Django 5.1.2 on 2024-10-21 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NMC_MCQ', '0003_alter_question_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.CharField(choices=[('Surgery', 'Surgery'), ('Medicine', 'Medicine'), ('Gyane', 'Gyane')], max_length=50),
        ),
    ]
